In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from xgboost  import XGBClassifier
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier,ExtraTreesClassifier,AdaBoostClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score, train_test_split,KFold, GroupKFold
from lightgbm import LGBMClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder

from sklearn.metrics import roc_auc_score

import tensorflow as tf
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint,ReduceLROnPlateau
from tensorflow.keras.layers import GlobalMaxPooling1D,BatchNormalization,Dense, Dropout, Input,Concatenate, LSTM, GRU,Bidirectional, Multiply

In [ ]:
df = pd.read_csv ('/content/finaldf.csv')

FileNotFoundError: ignored

In [ ]:
df

,Unnamed: 0,index00,index01,index02,index03,index04,index05,index06,index07,index08,...,index018,index019,index020,index021,index022,index023,index024,index025,index026,Output
0,0,6,5.0,0.7305,0.4294,0.5846,0.8909,0.8829,0.7973,0.6044,...,0.2827,0.1162,0.3238,0.9050,0.2084,0.2688,0.3755,0.9474,0.0612,0.0
1,1,6,6.0,0.5925,0.9305,0.8022,0.6491,0.8066,0.7540,0.3283,...,0.9898,0.9611,0.2367,0.2970,0.5353,0.9938,0.5797,0.6516,0.2664,0.0
2,2,6,7.0,0.4847,0.8088,0.4839,0.8089,0.7050,0.5451,0.3501,...,0.6434,0.4735,0.2680,0.9413,0.5229,0.8591,0.9311,0.4840,0.0957,0.0
3,3,6,8.0,0.2281,0.9681,0.0383,0.7566,0.5684,0.3047,0.1900,...,0.9549,0.6287,0.4710,0.5305,0.9662,0.9153,0.1227,0.4397,0.1833,0.0
4,4,6,9.0,0.0640,0.9625,0.9911,0.9439,0.3953,0.0869,0.1208,...,0.1863,0.3474,0.3129,0.7503,0.8748,0.5076,0.7052,0.4522,0.9273,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22007,22007,3492,3.0,0.8329,0.2602,0.5628,0.4443,0.0269,0.4013,0.6606,...,0.5368,0.9983,0.2179,0.5089,0.4157,0.2317,0.5089,0.0238,0.7893,1.0
22008,22008,3492,4.0,0.8759,0.3109,0.3389,0.6387,0.6774,0.8363,0.4716,...,0.9890,0.7081,0.3666,0.6961,0.0456,0.4550,0.2330,0.9926,0.6217,1.0
22009,22009,3492,5.0,0.6907,0.4084,0.8534,0.1996,0.3810,0.6426,0.0243,...,0.0663,0.8636,0.4733,0.8808,0.5697,0.8090,0.8185,0.2778,0.1756,1.0
22010,22010,3492,6.0,0.5147,0.2721,0.5793,0.6964,0.2648,0.2010,0.3871,...,0.9103,0.3427,0.2037,0.0634,0.4571,0.1518,0.0785,0.2695,0.5738,1.0
22011,22011,3492,7.0,0.9080,0.7880,0.3829,0.7266,0.0658,0.5072,0.1900,...,0.0738,0.9877,0.2150,0.6661,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_csv("train (1).csv", header = None)
df

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,0,1.0,0.4337,0.7431,0.9390,0.7541,0.9035,0.7943,0.2622,0.5901,...,0.5696,0.6407,0.7027,0.7163,0.9954,0.8303,0.1641,0.7893,0.7533,0.2925
1,0,2.0,0.7859,0.1925,0.9024,0.8108,0.2016,0.9649,0.2445,0.8934,...,0.4259,0.7456,0.5750,0.7947,0.4663,0.4303,0.3643,0.0558,0.1330,0.0295
2,0,3.0,0.0512,0.9633,0.1423,0.8404,0.6654,0.4348,0.5751,0.8067,...,0.4753,0.5449,0.8531,0.6337,0.8807,0.2560,0.0597,0.5751,0.7797,0.8544
3,0,4.0,0.0413,0.1588,0.1675,0.0971,0.2918,0.1970,0.0971,0.2039,...,0.7959,0.5306,0.3109,0.2726,0.3298,0.4658,0.7479,0.8747,0.2677,0.3816
4,0,5.0,0.7042,0.4724,0.3901,0.2793,0.2522,0.1933,0.2694,0.4110,...,0.2474,0.5711,0.5686,0.6575,0.1447,0.5774,0.4022,0.6753,0.8371,0.6748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63334,5757,8.0,0.6256,0.3680,0.2067,0.3257,0.7438,0.0178,0.1612,0.0965,...,0.3361,0.8291,0.6354,0.9523,0.0080,0.0531,0.3189,0.3033,0.8109,0.7813
63335,5757,9.0,0.0468,0.0783,0.0819,0.4191,0.8290,0.8320,0.9935,0.1458,...,0.3058,0.0789,0.3316,0.2331,0.5251,0.0134,0.5692,0.3030,0.6488,0.5215
63336,5757,10.0,0.3110,0.6507,0.7892,0.6143,0.4615,0.5193,0.6098,0.4886,...,0.2392,0.2505,0.3745,0.6171,0.1342,0.9817,0.9229,0.2131,0.2620,0.1048
63337,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63338,5758,1.0,0.7382,0.2754,0.6740,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
test = pd.read_csv('test.csv', header = None)
test

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,50000,1,0.3786,0.7031,0.0734,0.0492,0.8328,0.9048,0.7850,0.9979,...,0.6897,0.9130,0.5681,0.0129,0.4369,0.5533,0.2384,0.4805,0.3959,0.4756
1,50000,2,0.0871,0.3716,0.1444,0.4848,0.8051,0.6569,0.8121,0.5083,...,0.6067,0.1750,0.3267,0.1499,0.4746,0.2572,0.7884,0.3364,0.8252,0.8013
2,50000,3,0.7733,0.3273,0.0397,0.2026,0.7231,0.4640,0.2385,0.0435,...,0.2943,0.5956,0.4769,0.8894,0.8833,0.0786,0.4448,0.0071,0.4052,0.5436
3,50000,4,0.4817,0.6624,0.3319,0.7669,0.4364,0.1332,0.4890,0.7637,...,0.4996,0.2766,0.4083,0.9838,0.5823,0.3014,0.2781,0.1267,0.7782,0.1162
4,50000,5,0.0100,0.8568,0.5611,0.0171,0.2108,0.1046,0.4475,0.8220,...,0.2412,0.4066,0.2261,0.1200,0.8346,0.3691,0.5683,0.1112,0.7261,0.5521
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,50999,6,0.5563,0.0273,0.4050,0.0035,0.8710,0.3533,0.8382,0.5167,...,0.6842,0.8704,0.1593,0.1494,0.6192,0.2081,0.4659,0.8334,0.6913,0.2214
9996,50999,7,0.0702,0.7417,0.8893,0.3615,0.6888,0.5658,0.9178,0.6649,...,0.1328,0.3443,0.7526,0.0556,0.8064,0.5836,0.7398,0.6256,0.6917,0.8379
9997,50999,8,0.1935,0.8997,0.3039,0.9757,0.5910,0.5253,0.0459,0.3327,...,0.0930,0.1710,0.2240,0.8013,0.1723,0.4518,0.9341,0.5166,0.2043,0.9384
9998,50999,9,0.2718,0.7367,0.6270,0.8462,0.4284,0.4649,0.0397,0.3281,...,0.3151,0.1197,0.4840,0.5379,0.7549,0.3839,0.6309,0.8746,0.6079,0.4322
9999,50999,10,0.0469,0.0085,0.3151,0.5123,0.2128,0.2023,0.7841,0.9495,...,0.5829,0.4715,0.2034,0.5418,0.6209,0.7071,0.8569,0.7406,0.1911,0.3436

In [ ]:
names = ["sample_id", "Timepoint", "Sensor1", "Sensor2", "Sensor3", "Sensor4", "Sensor5", "Sensor6", "Sensor7", "Sensor8", "Sensor9", "Sensor10", "Sensor11", "Sensor12", "Sensor13", "Sensor14", "Sensor15", "Sensor16", "Sensor17", "Sensor18", "Sensor19", "Sensor20", "Sensor21", "Sensor22", "Sensor23", "Sensor24", "Sensor25"]

In [ ]:
df.columns = names
test.columns = names

In [ ]:
df.drop(df.tail(1).index,
        inplace = True)
df

,sample_id,Timepoint,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,...,Sensor16,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24,Sensor25
0,0,1.0,0.4337,0.7431,0.9390,0.7541,0.9035,0.7943,0.2622,0.5901,...,0.5696,0.6407,0.7027,0.7163,0.9954,0.8303,0.1641,0.7893,0.7533,0.2925
1,0,2.0,0.7859,0.1925,0.9024,0.8108,0.2016,0.9649,0.2445,0.8934,...,0.4259,0.7456,0.5750,0.7947,0.4663,0.4303,0.3643,0.0558,0.1330,0.0295
2,0,3.0,0.0512,0.9633,0.1423,0.8404,0.6654,0.4348,0.5751,0.8067,...,0.4753,0.5449,0.8531,0.6337,0.8807,0.2560,0.0597,0.5751,0.7797,0.8544
3,0,4.0,0.0413,0.1588,0.1675,0.0971,0.2918,0.1970,0.0971,0.2039,...,0.7959,0.5306,0.3109,0.2726,0.3298,0.4658,0.7479,0.8747,0.2677,0.3816
4,0,5.0,0.7042,0.4724,0.3901,0.2793,0.2522,0.1933,0.2694,0.4110,...,0.2474,0.5711,0.5686,0.6575,0.1447,0.5774,0.4022,0.6753,0.8371,0.6748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63333,5757,7.0,0.8866,0.4039,0.6354,0.7667,0.0987,0.1225,0.0508,0.2510,...,0.3666,0.3465,0.8090,0.5136,0.7435,0.2674,0.3006,0.3723,0.7507,0.8013
63334,5757,8.0,0.6256,0.3680,0.2067,0.3257,0.7438,0.0178,0.1612,0.0965,...,0.3361,0.8291,0.6354,0.9523,0.0080,0.0531,0.3189,0.3033,0.8109,0.7813
63335,5757,9.0,0.0468,0.0783,0.0819,0.4191,0.8290,0.8320,0.9935,0.1458,...,0.3058,0.0789,0.3316,0.2331,0.5251,0.0134,0.5692,0.3030,0.6488,0.5215
63336,5757,10.0,0.3110,0.6507,0.7892,0.6143,0.4615,0.5193,0.6098,0.4886,...,0.2392,0.2505,0.3745,0.6171,0.1342,0.9817,0.9229,0.2131,0.2620,0.1048
63337,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
label = df.loc[df['Timepoint'].isna(), 'sample_id'].tolist()
label

[1,
 2,
 3,
 1,
 1,
 1,
 3,
 0,
 2,
 0,
 3,
 3,
 1,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 2,
 0,
 0,
 1,
 0,
 1,
 1,
 3,
 2,
 3,
 0,
 2,
 1,
 2,
 3,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 2,
 3,
 2,
 3,
 0,
 3,
 3,
 3,
 0,
 2,
 0,
 3,
 1,
 3,
 2,
 1,
 3,
 2,
 0,
 2,
 3,
 0,
 3,
 3,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 1,
 2,
 0,
 3,
 2,
 2,
 1,
 1,
 3,
 1,
 2,
 0,
 3,
 0,
 0,
 0,
 1,
 0,
 3,
 3,
 0,
 2,
 0,
 3,
 1,
 0,
 2,
 1,
 3,
 0,
 3,
 1,
 2,
 2,
 2,
 1,
 1,
 3,
 2,
 0,
 3,
 2,
 2,
 3,
 3,
 0,
 0,
 0,
 2,
 3,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 3,
 1,
 0,
 0,
 2,
 1,
 2,
 1,
 3,
 1,
 0,
 0,
 3,
 2,
 1,
 1,
 3,
 1,
 0,
 3,
 0,
 0,
 1,
 1,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 2,
 3,
 1,
 0,
 0,
 3,
 0,
 2,
 0,
 2,
 3,
 1,
 0,
 3,
 2,
 3,
 0,
 0,
 1,
 0,
 1,
 3,
 3,
 1,
 3,
 1,
 3,
 1,
 1,
 2,
 0,
 2,
 3,
 1,
 1,
 3,
 1,
 1,
 1,
 0,
 2,
 3,
 3,
 0,
 0,
 2,
 1,
 2,
 0,
 0,
 0,
 3,
 1,
 0,
 0,
 2,
 1,
 0,
 3,
 3,
 3,
 3,
 2,
 2,
 0,
 0,
 3,
 3,
 0,
 0,
 2,
 2,
 0,
 3,
 1,
 3,
 1,
 0,
 3,
 2,
 0,
 3,
 1,
 2,
 0,
 3,
 1,
 0,
 3,
 1,
 0,
 0,
 2,
 3,
 3,
 0,
 0,
 0,
 2,
 1,
 0,
 3,
 3,
 3,
 0,
 1,
 0,
 0,
 0,
 3,
 1,
 3,
 0,
 0,
 0,
 2,
 2,
 3,
 2,
 1,
 3,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 2,
 3,
 2,
 3,
 3,
 2,
 0,
 2,
 0,
 3,
 3,
 2,
 3,
 0,
 1,
 2,
 0,
 3,
 3,
 3,
 2,
 0,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 0,
 3,
 2,
 3,
 1,
 1,
 0,
 0,
 0,
 0,
 3,
 2,
 3,
 3,
 2,
 3,
 0,
 0,
 0,
 0,
 0,
 3,
 0,
 1,
 2,
 0,
 1,
 2,
 3,
 2,
 1,
 3,
 0,
 0,
 3,
 1,
 2,
 2,
 1,
 3,
 2,
 0,
 2,
 3,
 3,
 0,
 2,
 1,
 3,
 0,
 3,
 3,
 0,
 3,
 2,
 2,
 0,
 3,
 0,
 1,
 3,
 0,
 1,
 3,
 0,
 1,
 3,
 2,
 0,
 3,
 3,
 1,
 2,
 0,
 3,
 1,
 0,
 1,
 2,
 3,
 2,
 1,
 0,
 0,
 3,
 3,
 1,
 2,
 3,
 3,
 3,
 2,
 0,
 3,
 1,
 0,
 3,
 3,
 0,
 0,
 2,
 2,
 2,
 3,
 3,
 2,
 0,
 3,
 1,
 3,
 2,
 3,
 1,
 0,
 3,
 3,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 3,
 1,
 3,
 0,
 2,
 0,
 1,
 1,
 2,
 3,
 3,
 3,
 0,
 2,
 0,
 3,
 2,
 2,
 3,
 1,
 0,
 2,
 0,
 0,
 3,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 3,
 3,
 2,
 3,
 2,
 2,
 1,
 3,
 2,
 3,
 1,
 0,
 3,
 3,
 3,
 3,
 2,
 0,
 3,
 0,
 2,
 3,
 3,
 3,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 3,
 1,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 0,
 0,
 1,
 1,
 0,
 1,
 3,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 0,
 1,
 0,
 3,
 3,
 3,
 2,
 3,
 1,
 2,
 1,
 2,
 2,
 3,
 3,
 1,
 0,
 2,
 0,
 3,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 2,
 3,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 2,
 2,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 1,
 3,
 0,
 2,
 2,
 0,
 2,
 1,
 3,
 1,
 3,
 0,
 3,
 0,
 3,
 0,
 0,
 0,
 1,
 3,
 2,
 1,
 0,
 3,
 0,
 0,
 3,
 2,
 0,
 3,
 1,
 2,
 1,
 3,
 0,
 1,
 0,
 1,
 1,
 2,
 2,
 2,
 2,
 0,
 3,
 3,
 3,
 2,
 1,
 3,
 3,
 3,
 0,
 3,
 3,
 0,
 0,
 3,
 2,
 3,
 3,
 2,
 3,
 2,
 0,
 3,
 2,
 3,
 3,
 3,
 1,
 0,
 2,
 2,
 1,
 3,
 0,
 1,
 2,
 2,
 0,
 1,
 0,
 0,
 0,
 3,
 1,
 1,
 3,
 1,
 2,
 0,
 0,
 2,
 0,
 0,
 3,
 0,
 0,
 1,
 3,
 2,
 0,
 3,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 3,
 1,
 3,
 0,
 3,
 0,
 0,
 3,
 2,
 3,
 3,
 0,
 1,
 3,
 1,
 2,
 1,
 3,
 2,
 2,
 0,
 0,
 2,
 3,
 0,
 1,
 3,
 1,
 0,
 3,
 3,
 3,
 2,
 1,
 2,
 3,
 3,
 0,
 0,
 1,
 1,
 2,
 2,
 3,
 1,
 2,
 1,
 0,
 1,
 1,
 3,
 0,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 3,
 0,
 2,
 3,
 2,
 3,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 2,
 3,
 3,
 1,
 0,
 3,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 3,
 3,
 3,
 3,
 0,
 3,
 3,
 1,
 3,
 3,
 0,
 1,
 3,
 2,
 0,
 2,
 2,
 0,
 3,
 0,
 0,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 2,
 0,
 0,
 1,
 0,
 1,
 3,
 0,
 0,
 3,
 0,
 0,
 0,
 2,
 2,
 3,
 0,
 1,
 3,
 3,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 3,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 2,
 0,
 0,
 3,
 1,
 0,
 0,
 1,
 2,
 2,
 0,
 3,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 2,
 1,
 0,
 2,
 1,
 2,
 3,
 0,
 2,
 3,
 3,
 1,
 1,
 3,
 2,
 3,
 1,
 1,
 1,
 3,
 2,
 3,
 1,
 0,
 3,
 0,
 0,
 3,
 0,
 0,
 3,
 0,
 0,
 0,
 3,
 3,
 0,
 2,
 0,
 3,
 1,
 3,
 3,
 1,
 3,
 3,
 2,
 3,
 0,
 0,
 2,
 0,
 2,
 0,
 1,
 1,
 0,
 3,
 3,
 0,
 1,
 1,
 1,
 2,
 1,
 3,
 3,
 1,
 3,
 1,
 3,
 1,
 0,
 0,
 0,
 3,
 3,
 2,
 2,
 1,
 ...]

In [ ]:
t_lbls = pd.DataFrame(label,columns = ["target"])
t_lbls = t_lbls.reset_index()
t_lbls = t_lbls.rename(columns = {"index": "sample_id"})
t_lbls

      sample_id  target
0             0       1
1             1       2
2             2       3
3             3       1
4             4       1
...         ...     ...
5753       5753       3
5754       5754       2
5755       5755       2
5756       5756       3
5757       5757       1

[5758 rows x 2 columns]

In [ ]:
df = df.dropna(subset=['Timepoint'])
df

,sample_id,Timepoint,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,...,Sensor16,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24,Sensor25
0,0,1.0,0.4337,0.7431,0.9390,0.7541,0.9035,0.7943,0.2622,0.5901,...,0.5696,0.6407,0.7027,0.7163,0.9954,0.8303,0.1641,0.7893,0.7533,0.2925
1,0,2.0,0.7859,0.1925,0.9024,0.8108,0.2016,0.9649,0.2445,0.8934,...,0.4259,0.7456,0.5750,0.7947,0.4663,0.4303,0.3643,0.0558,0.1330,0.0295
2,0,3.0,0.0512,0.9633,0.1423,0.8404,0.6654,0.4348,0.5751,0.8067,...,0.4753,0.5449,0.8531,0.6337,0.8807,0.2560,0.0597,0.5751,0.7797,0.8544
3,0,4.0,0.0413,0.1588,0.1675,0.0971,0.2918,0.1970,0.0971,0.2039,...,0.7959,0.5306,0.3109,0.2726,0.3298,0.4658,0.7479,0.8747,0.2677,0.3816
4,0,5.0,0.7042,0.4724,0.3901,0.2793,0.2522,0.1933,0.2694,0.4110,...,0.2474,0.5711,0.5686,0.6575,0.1447,0.5774,0.4022,0.6753,0.8371,0.6748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63332,5757,6.0,0.2841,0.2035,0.9374,0.4092,0.1831,0.9451,0.2588,0.7959,...,0.8382,0.6800,0.5346,0.5007,0.2533,0.6173,0.4566,0.7001,0.3758,0.8624
63333,5757,7.0,0.8866,0.4039,0.6354,0.7667,0.0987,0.1225,0.0508,0.2510,...,0.3666,0.3465,0.8090,0.5136,0.7435,0.2674,0.3006,0.3723,0.7507,0.8013
63334,5757,8.0,0.6256,0.3680,0.2067,0.3257,0.7438,0.0178,0.1612,0.0965,...,0.3361,0.8291,0.6354,0.9523,0.0080,0.0531,0.3189,0.3033,0.8109,0.7813
63335,5757,9.0,0.0468,0.0783,0.0819,0.4191,0.8290,0.8320,0.9935,0.1458,...,0.3058,0.0789,0.3316,0.2331,0.5251,0.0134,0.5692,0.3030,0.6488,0.5215
63336,5757,10.0,0.3110,0.6507,0.7892,0.6143,0.4615,0.5193,0.6098,0.4886,...,0.2392,0.2505,0.3745,0.6171,0.1342,0.9817,0.9229,0.2131,0.2620,0.1048

In [ ]:
df.describe()

,sample_id,Timepoint,Sensor1,Sensor2,Sensor3,Sensor4,Sensor5,Sensor6,Sensor7,Sensor8,...,Sensor16,Sensor17,Sensor18,Sensor19,Sensor20,Sensor21,Sensor22,Sensor23,Sensor24,Sensor25
count,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,...,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000,57580.000000
mean,2878.500000,5.500000,0.500071,0.502503,0.500006,0.501132,0.501600,0.502420,0.500007,0.502448,...,0.499751,0.499949,0.499906,0.498128,0.498542,0.502253,0.500924,0.500230,0.499572,0.500823
std,1662.205834,2.872306,0.288933,0.287993,0.289147,0.289111,0.287568,0.288486,0.288475,0.288562,...,0.288908,0.287861,0.289158,0.289070,0.288033,0.288287,0.288564,0.288576,0.288720,0.288240
min,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000100
25%,1439.000000,3.000000,0.250900,0.253300,0.247400,0.250500,0.254600,0.253800,0.249200,0.254200,...,0.250400,0.251200,0.247000,0.245700,0.249375,0.253100,0.252300,0.250600,0.249600,0.252000
50%,2878.500000,5.500000,0.499900,0.503050,0.502400,0.501900,0.503200,0.502150,0.502300,0.501200,...,0.501200,0.498300,0.501400,0.498300,0.497400,0.502500,0.501100,0.500550,0.500700,0.501000
75%,4318.000000,8.000000,0.749300,0.752100,0.749700,0.752100,0.748400,0.751700,0.747100,0.753425,...,0.749900,0.748325,0.749600,0.748900,0.747400,0.752125,0.750500,0.748300,0.749100,0.749800
max,5757.000000,10.000000,1.000000,0.999900,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
features = df.columns.tolist()[2:]

In [ ]:
features

['Sensor1',
 'Sensor2',
 'Sensor3',
 'Sensor4',
 'Sensor5',
 'Sensor6',
 'Sensor7',
 'Sensor8',
 'Sensor9',
 'Sensor10',
 'Sensor11',
 'Sensor12',
 'Sensor13',
 'Sensor14',
 'Sensor15',
 'Sensor16',
 'Sensor17',
 'Sensor18',
 'Sensor19',
 'Sensor20',
 'Sensor21',
 'Sensor22',
 'Sensor23',
 'Sensor24',
 'Sensor25']

In [ ]:
def prep(df):
    for feature in features:
        df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
        df.fillna(0, inplace=True)
        df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']

prep(df)
prep(test)
sc = StandardScaler()
df[features] = sc.fit_transform(df[features])
test[features] = sc.transform(test[features])

groups = df["sample_id"]
labels = t_lbls["target"]

<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_diff1'] = df[feature] - df[feature + '_lag1']
<ipython-input-15-e9902e77b093>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature + '_lag1'] = df.groupby('sample_id')[feature].shift(1)
<ipython-input-15-e9902e77b093>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)
<ipython-input-15-e9902e77b093>:5: SettingWithCopyWarning:

In [ ]:
train = df.drop(["Timepoint", "sample_id"], axis=1).values
train = train.reshape(-1, 10, train.shape[-1])

test = test.drop(["Timepoint", "sample_id"], axis=1).values
test = test.reshape(-1, 10, test.shape[-1])

In [ ]:
train.shape

(5758, 10, 75)

In [ ]:
def dnn_model():

    x_input = Input(shape=(train.shape[-2:]))

    x0 = Bidirectional(LSTM(units=256, return_sequences=True))(x_input)
    x1 = Bidirectional(LSTM(units=512, return_sequences=True))(x0)
    x2 = Bidirectional(LSTM(units=256, return_sequences=True))(x1)
    z1 = Bidirectional(GRU(units=256, return_sequences=True))(x1)

    c = Concatenate(axis=2)([x2, z1])

    x3 = Bidirectional(LSTM(units=256, return_sequences=True))(c)

    x4 = GlobalMaxPooling1D()(x3)
    x5 = Dense(units=128, activation='selu')(x4)
    x_output = Dense(4, activation='softmax')(x5)
    #x_output =  tf.round(tf.argmax(x_output, axis=-1)) # use tf.argmax here
    model = Model(inputs=x_input, outputs=x_output, name='lstm_model')

    return model

model = dnn_model()

In [ ]:
print(np.bincount(labels))
labels = pd.get_dummies(labels)
print(labels)

[1591 1268 1292 1607]
      0  1  2  3
0     0  1  0  0
1     0  0  1  0
2     0  0  0  1
3     0  1  0  0
4     0  1  0  0
...  .. .. .. ..
5753  0  0  0  1
5754  0  0  1  0
5755  0  0  1  0
5756  0  0  0  1
5757  0  1  0  0

[5758 rows x 4 columns]

In [ ]:
try:
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)
    BATCH_SIZE = tpu_strategy.num_replicas_in_sync * 64
    print("Running on TPU:", tpu.master())
    print(f"Batch Size: {BATCH_SIZE}")

except ValueError:
    strategy = tf.distribute.get_strategy()
    BATCH_SIZE = 256
    print(f"Running on {strategy.num_replicas_in_sync} replicas")
    print(f"Batch Size: {BATCH_SIZE}")

Running on 1 replicas
Batch Size: 256

In [ ]:
VERBOSE = 64
    #BATCH_SIZE = 4
predictions, scores = [], []
k = GroupKFold(n_splits = 6)

for fold, (train_idx, val_idx) in enumerate(k.split(train, labels, groups.unique())):
        print('-'*15, '>', f'Fold {fold+1}', '<', '-'*15)

        X_train, X_val = train[train_idx], train[val_idx]
        y_train, y_val = labels.iloc[train_idx].values, labels.iloc[val_idx].values

        model = dnn_model()
        model.compile(optimizer="adam", loss='categorical_crossentropy', metrics='AUC')

        lr = ReduceLROnPlateau(monitor="val_auc", factor=0.6,
                               patience=5, verbose=VERBOSE)

        es = EarlyStopping(monitor="val_auc", patience=10,
                           verbose=VERBOSE, mode="max",
                           restore_best_weights=True)

        save_locally = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
        chk_point = ModelCheckpoint(f'./TPS_model_1_2022_{fold+1}C.h5', options=save_locally,
                                    monitor='val_auc', verbose=VERBOSE,
                                    save_best_only=True, mode='max')

        model.fit(X_train, y_train,
                  validation_data=(X_val, y_val),
                  epochs=25,
                  verbose=VERBOSE,
                  batch_size=BATCH_SIZE,
                  callbacks=[lr, chk_point, es])

        load_locally = tf.saved_model.LoadOptions(experimental_io_device='/job:localhost')
        model = load_model(f'./TPS_model_1_2022_{fold+1}C.h5', options=load_locally)

        y_pred = model.predict(X_val, batch_size=BATCH_SIZE).squeeze()
        score = roc_auc_score(y_val, y_pred)
        scores.append(score)
        predictions.append(model.predict(test, batch_size=BATCH_SIZE).squeeze())
        print(f"model1,Fold-{fold+1} | OOF Score: {score}")

print(f'Mean accuracy on {k.n_splits} folds - {np.mean(scores)}')

--------------- > Fold 1 < ---------------
Epoch 1/25

Epoch 1: val_auc improved from -inf to 0.55140, saving model to ./TPS_model_1_2022_1C.h5
Epoch 2/25

Epoch 2: val_auc did not improve from 0.55140
Epoch 3/25

Epoch 3: val_auc improved from 0.55140 to 0.55445, saving model to ./TPS_model_1_2022_1C.h5
Epoch 4/25

Epoch 4: val_auc improved from 0.55445 to 0.56993, saving model to ./TPS_model_1_2022_1C.h5
Epoch 5/25

Epoch 5: val_auc improved from 0.56993 to 0.59814, saving model to ./TPS_model_1_2022_1C.h5
Epoch 6/25

Epoch 6: val_auc did not improve from 0.59814
Epoch 7/25

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.

Epoch 7: val_auc improved from 0.59814 to 0.60897, saving model to ./TPS_model_1_2022_1C.h5
Epoch 8/25

Epoch 8: val_auc improved from 0.60897 to 0.61521, saving model to ./TPS_model_1_2022_1C.h5
Epoch 9/25

Epoch 9: val_auc did not improve from 0.61521
Epoch 10/25

Epoch 10: val_auc did not improve from 0.61521
Epoch 11/25

Epoch 11: val_auc did not improve from 0.61521
Epoch 12/25

Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0003600000170990825.

Epoch 12: val_auc did not improve from 0.61521
Epoch 13/25

Epoch 13: val_auc did not improve from 0.61521
Epoch 14/25

Epoch 14: val_auc did not improve from 0.61521
Epoch 15/25

Epoch 15: val_auc did not improve from 0.61521
Epoch 16/25

Epoch 16: val_auc did not improve from 0.61521
Epoch 17/25

Epoch 17: ReduceLROnPlateau reducing learning rate to 0.00021600000327453016.

Epoch 17: val_auc did not improve from 0.61521
Epoch 18/25

Epoch 18: val_auc did not improve from 0.61521
Restoring model weights from the end of the best epoch: 8.
Epoch 18: early stopping
4/4 [==============================] - 9s 1s/step
4/4 [==============================] - 6s 1s/step
model1,Fold-1 | OOF Score: 0.612972140300367
--------------- > Fold 2 < ---------------
Epoch 1/25

Epoch 1: val_auc improved from -inf to 0.53415, saving model to ./TPS_model_1_2022_2C.h5
Epoch 2/25

Epoch 2: val_auc did not improve from 0.53415
Epoch 3/25

Epoch 3: val_auc improved from 0.53415 to 0.54272, saving model to ./TPS_model_1_2022_2C.h5
Epoch 4/25

Epoch 4: val_auc improved from 0.54272 to 0.55465, saving model to ./TPS_model_1_2022_2C.h5
Epoch 5/25

Epoch 5: val_auc improved from 0.55465 to 0.58237, saving model to ./TPS_model_1_2022_2C.h5
Epoch 6/25

Epoch 6: val_auc improved from 0.58237 to 0.60402, saving model to ./TPS_model_1_2022_2C.h5
Epoch 7/25

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.

Epoch 7: val_auc improved from 0.60402 to 0.61201, saving model to ./TPS_model_1_2022_2C.h5
Epoch 8/25

Epoch 8: val_auc improved from 0.61201 to 0.61601, saving model to ./TPS_model_1_2022_2C.h5
Epoch 9/25

Epoch 9: val_auc did not improve from 0.61601
Epoch 10/25

Epoch 10: val_auc did not improve from 0.61601
Epoch 11/25

Epoch 11: val_auc did not improve from 0.61601
Epoch 12/25

Epoch 12: ReduceLROnPlateau reducing learning rate to 0.0003600000170990825.

Epoch 12: val_auc did not improve from 0.61601
Epoch 13/25

Epoch 13: val_auc did not improve from 0.61601
Epoch 14/25

Epoch 14: val_auc did not improve from 0.61601
Epoch 15/25

Epoch 15: val_auc did not improve from 0.61601
Epoch 16/25

Epoch 16: val_auc did not improve from 0.61601
Epoch 17/25

Epoch 17: ReduceLROnPlateau reducing learning rate to 0.00021600000327453016.

Epoch 17: val_auc did not improve from 0.61601
Epoch 18/25

Epoch 18: val_auc did not improve from 0.61601
Restoring model weights from the end of the best epoch: 8.
Epoch 18: early stopping
4/4 [==============================] - 10s 1s/step
4/4 [==============================] - 5s 1s/step
model1,Fold-2 | OOF Score: 0.6097975647644959
--------------- > Fold 3 < ---------------
Epoch 1/25

Epoch 1: val_auc improved from -inf to 0.49930, saving model to ./TPS_model_1_2022_3C.h5
Epoch 2/25

Epoch 2: val_auc improved from 0.49930 to 0.53360, saving model to ./TPS_model_1_2022_3C.h5
Epoch 3/25

Epoch 3: val_auc did not improve from 0.53360
Epoch 4/25

Epoch 4: val_auc improved from 0.53360 to 0.54956, saving model to ./TPS_model_1_2022_3C.h5
Epoch 5/25

Epoch 5: val_auc improved from 0.54956 to 0.57670, saving model to ./TPS_model_1_2022_3C.h5
Epoch 6/25

Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0006000000284984708.

Epoch 6: val_auc did not improve from 0.57670
Epoch 7/25

Epoch 7: val_auc improved from 0.57670 to 0.59272, saving model to ./TPS_model_1_2022_3C.h5
Epoch 8/25

Epoch 8: val_auc did not improve from 0.59272
Epoch 9/25

Epoch 9: val_auc did not improve from 0.59272
Epoch 10/25

Epoch 10: val_auc did not improve from 0.59272
Epoch 11/25

Epoch 11: ReduceLROnPlateau reducing learning rate to 0.0003600000170990825.

Epoch 11: val_auc did not improve from 0.59272
Epoch 12/25

Epoch 12: val_auc did not improve from 0.59272
Epoch 13/25

Epoch 13: val_auc did not improve from 0.59272
Epoch 14/25

Epoch 14: val_auc did not improve from 0.59272
Epoch 15/25

Epoch 15: val_auc did not improve from 0.59272
Epoch 16/25

Epoch 16: ReduceLROnPlateau reducing learning rate to 0.00021600000327453016.

Epoch 16: val_auc did not improve from 0.59272
Epoch 17/25

Epoch 17: val_auc did not improve from 0.59272
Restoring model weights from the end of the best epoch: 7.
Epoch 17: early stopping
4/4 [==============================] - 10s 1s/step
4/4 [==============================] - 5s 1s/step
model1,Fold-3 | OOF Score: 0.587622654314177
--------------- > Fold 4 < ---------------
Epoch 1/25

Epoch 1: val_auc improved from -inf to 0.54413, saving model to ./TPS_model_1_2022_4C.h5
Epoch 2/25

Epoch 2: val_auc did not improve from 0.54413
Epoch 3/25

In [ ]:

y_val = np.round(np.argmax(y_val, axis =1))
y_val

In [ ]:
y_pred =  np.round(np.argmax(y_pred, axis =1))
y_pred

In [ ]:
np.mean(y_pred == y_val)

In [ ]:
predictions

In [ ]:
def dnn_model2():

    x_input = Input(shape=(train.shape[-2:]))
    xi = Bidirectional(LSTM(units=128, return_sequences=True))(x_input)
    x0 = Bidirectional(LSTM(units=256, return_sequences=True))(xi)
    x00 = Bidirectional(LSTM(units=512, return_sequences=True))(x0)
    x1 = Bidirectional(LSTM(units=256, return_sequences=True))(x00)

    x2 = Bidirectional(LSTM(units=256, return_sequences=True))(x1)
    z1 = Bidirectional(GRU(units=256, return_sequences=True))(x1)

    c = Concatenate(axis=2)([x2, z1])

    x3 = Bidirectional(LSTM(units=256, return_sequences=True))(c)

    x4 = GlobalMaxPooling1D()(x3)
    x5 = Dense(units=128, activation='selu')(x4)
    x6 = Dense(units=64, activation='selu')(x5)
    x_output = Dense(4, activation='softmax')(x6)

    model = Model(inputs=x_input, outputs=x_output, name='lstm_model2')

    return model

model2 = dnn_model2()

In [ ]:
VERBOSE = 64
#   BATCH_SIZE = 256
predictions, scores,accuracy = [], [],[]
k = GroupKFold(n_splits = 6)

for fold, (train_idx, val_idx) in enumerate(k.split(train, labels, groups.unique())):
        print('-'*15, '>', f'Fold {fold+1}', '<', '-'*15)

        X_train, X_val = train[train_idx], train[val_idx]
        y_train, y_val = labels.iloc[train_idx].values, labels.iloc[val_idx].values

        model = dnn_model()
        model.compile(optimizer="adam", loss="categorical_crossentropy", metrics='AUC')

        lr = ReduceLROnPlateau(monitor="val_auc", factor=0.6,
                               patience=5, verbose=VERBOSE)

        es = EarlyStopping(monitor="val_auc", patience=10,
                           verbose=VERBOSE, mode="max",
                           restore_best_weights=True)

        save_locally = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
        chk_point = ModelCheckpoint(f'./TPS_model_1_2022_{fold+1}C.h5', options=save_locally,
                                    monitor='val_auc', verbose=VERBOSE,
                                    save_best_only=True, mode='max')

        model.fit(X_train, y_train,
                  validation_data=(X_val, y_val),
                  epochs=25,
                  verbose=VERBOSE,
                  batch_size=BATCH_SIZE,
                  callbacks=[lr, chk_point, es])

        load_locally = tf.saved_model.LoadOptions(experimental_io_device='/job:localhost')
        model = load_model(f'./TPS_model_1_2022_{fold+1}C.h5', options=load_locally)

        y_pred = model.predict(X_val, batch_size=BATCH_SIZE).squeeze()
        score = roc_auc_score(y_val, y_pred)
        scores.append(score)
        correct_predictions = tf.equal(tf.argmax(y_val, axis=1), tf.argmax(y_pred, axis=1))
        acc = tf.reduce_mean(tf.cast(correct_predictions, tf.float32))
        accuracy.append(acc.numpy())
        predictions.append(model.predict(test, batch_size=BATCH_SIZE).squeeze())
        print(f"model1,Fold-{fold+1} | OOF Score: {score}")

print(f'Mean accuracy on {k.n_splits} folds - {np.mean(scores)}')

In [ ]:
accuracy

In [ ]:
##